// Code generated by MockGen. DO NOT EDIT.
// Source: ingest.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	ingest "github.com/xeptore/wireuse/ingest"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// IngestUsage mocks base method.
func (m *MockStore) IngestUsage(ctx context.Context, peersUsage []ingest.PeerUsage, gatheredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestUsage", ctx, peersUsage, gatheredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// IngestUsage indicates an expected call of IngestUsage.
func (mr *MockStoreMockRecorder) IngestUsage(ctx, peersUsage, gatheredAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestUsage", reflect.TypeOf((*MockStore)(nil).IngestUsage), ctx, peersUsage, gatheredAt)
}

// LoadUsage mocks base method.
func (m *MockStore) LoadUsage(ctx context.Context) (map[string]ingest.PeerUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadUsage", ctx)
	ret0, _ := ret[0].(map[string]ingest.PeerUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadUsage indicates an expected call of LoadUsage.
func (mr *MockStoreMockRecorder) LoadUsage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadUsage", reflect.TypeOf((*MockStore)(nil).LoadUsage), ctx)
}

// MockWgPeers is a mock of WgPeers interface.
type MockWgPeers struct {
	ctrl     *gomock.Controller
	recorder *MockWgPeersMockRecorder
}

// MockWgPeersMockRecorder is the mock recorder for MockWgPeers.
type MockWgPeersMockRecorder struct {
	mock *MockWgPeers
}

// NewMockWgPeers creates a new mock instance.
func NewMockWgPeers(ctrl *gomock.Controller) *MockWgPeers {
	mock := &MockWgPeers{ctrl: ctrl}
	mock.recorder = &MockWgPeersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWgPeers) EXPECT() *MockWgPeersMockRecorder {
	return m.recorder
}

// Usage mocks base method.
func (m *MockWgPeers) Usage(ctx context.Context) ([]ingest.PeerUsage, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage", ctx)
	ret0, _ := ret[0].([]ingest.PeerUsage)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Usage indicates an expected call of Usage.
func (mr *MockWgPeersMockRecorder) Usage(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockWgPeers)(nil).Usage), ctx)
}
