name: Build
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    env:
      GOPROXY: https://goproxy.io,direct
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: false
          check-latest: true
      - name: Tidy
        run: make tidy
      - name: Build
        run: make build-clean
      - name: Test
        run: make test
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ingest
          path: ./bin/ingest_linux_amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./bin/ingest_linux_amd64
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/ingest
          tags: |
            type=edge,enable=${{ github.event_name == 'push' && github.ref_protected && github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
          flavor: |
            latest=${{ github.ref_type != 'tag' && !startsWith(github.ref, 'refs/tags/') }}
            prefix=,onlatest=false
            suffix=,onlatest=false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: docker_build_and_push
        uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          context: .
          file: Dockerfile
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository }}/ingest:latest
          labels: ${{ steps.meta.outputs.labels }}
        timeout-minutes: 10
