name: Build And Publish Docker Image
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    concurrency:
      cancel-in-progress: false
      group: ${{ format('{0}-{1}', github.event_name, github.ref_name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/ingest
          tags: |
            type=edge
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_and_push
        uses: docker/build-push-action@v4
        with:
          push: true
          pull: true
          context: .
          file: Dockerfile
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository }}/ingest:latest
          labels: ${{ steps.meta.outputs.labels }}
        timeout-minutes: 10